databases:
  - name: budgettrackie
    databaseName: budgettrackie
    user: budgettrackie_user

services:
  - type: web
    name: budgettrackie
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgettrackie
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false